#############################################################################
# Makefile for building: installer
# Generated by qmake (2.01a) (Qt 4.8.2) on: Fri Oct 12 15:09:04 2012
# Project:  installer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile installer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -IPages -ISystem -IDelegates -IWidgets -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lsysfs -lparted -lblkid -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Delegates/checkBoxListDelegate.cpp \
		Delegates/comboBoxListDelegate.cpp \
		Delegates/paritionSizeDelegate.cpp \
		Delegates/progressbarDelegate.cpp \
		Pages/diskPage.cpp \
		Pages/licensePage.cpp \
		Pages/loadingpage.cpp \
		Pages/packagesPage.cpp \
		Pages/pageBase.cpp \
		Pages/releasePage.cpp \
		Pages/timepage.cpp \
		Pages/userspage.cpp \
		System/drive.cpp \
		Widgets/checkBoxList.cpp \
		System/rootCommand.cpp \
		Pages/configurationPage.cpp \
		Pages/installationPage.cpp \
		System/chroot.cpp moc_mainwindow.cpp \
		moc_checkBoxListDelegate.cpp \
		moc_comboBoxListDelegate.cpp \
		moc_partitionSizeDelegate.cpp \
		moc_progressbarDelegate.cpp \
		moc_diskPage.cpp \
		moc_licensePage.cpp \
		moc_loadingpage.cpp \
		moc_packagesPage.cpp \
		moc_pageBase.cpp \
		moc_releasePage.cpp \
		moc_timepage.cpp \
		moc_userspage.cpp \
		moc_checkBoxList.cpp \
		moc_rootCommand.cpp \
		moc_configurationPage.cpp \
		moc_installationPage.cpp \
		moc_chroot.cpp \
		qrc_Resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		checkBoxListDelegate.o \
		comboBoxListDelegate.o \
		paritionSizeDelegate.o \
		progressbarDelegate.o \
		diskPage.o \
		licensePage.o \
		loadingpage.o \
		packagesPage.o \
		pageBase.o \
		releasePage.o \
		timepage.o \
		userspage.o \
		drive.o \
		checkBoxList.o \
		rootCommand.o \
		configurationPage.o \
		installationPage.o \
		chroot.o \
		moc_mainwindow.o \
		moc_checkBoxListDelegate.o \
		moc_comboBoxListDelegate.o \
		moc_partitionSizeDelegate.o \
		moc_progressbarDelegate.o \
		moc_diskPage.o \
		moc_licensePage.o \
		moc_loadingpage.o \
		moc_packagesPage.o \
		moc_pageBase.o \
		moc_releasePage.o \
		moc_timepage.o \
		moc_userspage.o \
		moc_checkBoxList.o \
		moc_rootCommand.o \
		moc_configurationPage.o \
		moc_installationPage.o \
		moc_chroot.o \
		qrc_Resources.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		installer.pro
QMAKE_TARGET  = installer
DESTDIR       = 
TARGET        = installer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_diskPage.h ui_licensePage.h ui_loadingPage.h ui_mainwindow.h ui_packagesPage.h ui_releasePage.h ui_timepage.h ui_usersPage.h ui_configurationPage.h ui_installationPage.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: installer.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile installer.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile installer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/installer1.0.0 || $(MKDIR) .tmp/installer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/installer1.0.0/ && $(COPY_FILE) --parents mainwindow.h ui_loadingPage.h Delegates/checkBoxListDelegate.hpp Delegates/comboBoxListDelegate.hpp Delegates/partitionSizeDelegate.hpp Delegates/progressbarDelegate.hpp Pages/diskPage.hpp Pages/licensePage.hpp Pages/loadingpage.hpp Pages/packagesPage.hpp Pages/pageBase.hpp Pages/releasePage.hpp Pages/timepage.hpp Pages/userspage.hpp System/drive.h System/driveList.h Widgets/checkBoxList.hpp System/rootCommand.hpp Pages/configurationPage.hpp Pages/installationPage.hpp System/chroot.hpp .tmp/installer1.0.0/ && $(COPY_FILE) --parents Resources.qrc .tmp/installer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp Delegates/checkBoxListDelegate.cpp Delegates/comboBoxListDelegate.cpp Delegates/paritionSizeDelegate.cpp Delegates/progressbarDelegate.cpp Pages/diskPage.cpp Pages/licensePage.cpp Pages/loadingpage.cpp Pages/packagesPage.cpp Pages/pageBase.cpp Pages/releasePage.cpp Pages/timepage.cpp Pages/userspage.cpp System/drive.cpp Widgets/checkBoxList.cpp System/rootCommand.cpp Pages/configurationPage.cpp Pages/installationPage.cpp System/chroot.cpp .tmp/installer1.0.0/ && $(COPY_FILE) --parents UI/diskPage.ui UI/licensePage.ui UI/loadingPage.ui UI/mainwindow.ui UI/packagesPage.ui UI/releasePage.ui UI/timepage.ui UI/usersPage.ui UI/configurationPage.ui UI/installationPage.ui .tmp/installer1.0.0/ && $(COPY_FILE) --parents Translations/en.ts Translations/ar.ts .tmp/installer1.0.0/ && (cd `dirname .tmp/installer1.0.0` && $(TAR) installer1.0.0.tar installer1.0.0 && $(COMPRESS) installer1.0.0.tar) && $(MOVE) `dirname .tmp/installer1.0.0`/installer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/installer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_checkBoxListDelegate.cpp moc_comboBoxListDelegate.cpp moc_partitionSizeDelegate.cpp moc_progressbarDelegate.cpp moc_diskPage.cpp moc_licensePage.cpp moc_loadingpage.cpp moc_packagesPage.cpp moc_pageBase.cpp moc_releasePage.cpp moc_timepage.cpp moc_userspage.cpp moc_checkBoxList.cpp moc_rootCommand.cpp moc_configurationPage.cpp moc_installationPage.cpp moc_chroot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_checkBoxListDelegate.cpp moc_comboBoxListDelegate.cpp moc_partitionSizeDelegate.cpp moc_progressbarDelegate.cpp moc_diskPage.cpp moc_licensePage.cpp moc_loadingpage.cpp moc_packagesPage.cpp moc_pageBase.cpp moc_releasePage.cpp moc_timepage.cpp moc_userspage.cpp moc_checkBoxList.cpp moc_rootCommand.cpp moc_configurationPage.cpp moc_installationPage.cpp moc_chroot.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_checkBoxListDelegate.cpp: Delegates/checkBoxListDelegate.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Delegates/checkBoxListDelegate.hpp -o moc_checkBoxListDelegate.cpp

moc_comboBoxListDelegate.cpp: Delegates/comboBoxListDelegate.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Delegates/comboBoxListDelegate.hpp -o moc_comboBoxListDelegate.cpp

moc_partitionSizeDelegate.cpp: Delegates/partitionSizeDelegate.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Delegates/partitionSizeDelegate.hpp -o moc_partitionSizeDelegate.cpp

moc_progressbarDelegate.cpp: Delegates/progressbarDelegate.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Delegates/progressbarDelegate.hpp -o moc_progressbarDelegate.cpp

moc_diskPage.cpp: System/drive.h \
		Pages/pageBase.hpp \
		ui_diskPage.h \
		Delegates/partitionSizeDelegate.hpp \
		Delegates/comboBoxListDelegate.hpp \
		Pages/diskPage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/diskPage.hpp -o moc_diskPage.cpp

moc_licensePage.cpp: Pages/pageBase.hpp \
		ui_licensePage.h \
		Pages/licensePage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/licensePage.hpp -o moc_licensePage.cpp

moc_loadingpage.cpp: Pages/pageBase.hpp \
		ui_loadingPage.h \
		Pages/loadingpage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/loadingpage.hpp -o moc_loadingpage.cpp

moc_packagesPage.cpp: ui_packagesPage.h \
		Pages/pageBase.hpp \
		Pages/packagesPage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/packagesPage.hpp -o moc_packagesPage.cpp

moc_pageBase.cpp: Pages/pageBase.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/pageBase.hpp -o moc_pageBase.cpp

moc_releasePage.cpp: Pages/pageBase.hpp \
		ui_releasePage.h \
		Pages/releasePage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/releasePage.hpp -o moc_releasePage.cpp

moc_timepage.cpp: Pages/pageBase.hpp \
		ui_timepage.h \
		Pages/timepage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/timepage.hpp -o moc_timepage.cpp

moc_userspage.cpp: Pages/pageBase.hpp \
		ui_usersPage.h \
		Widgets/checkBoxList.hpp \
		Delegates/checkBoxListDelegate.hpp \
		Pages/userspage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/userspage.hpp -o moc_userspage.cpp

moc_checkBoxList.cpp: Delegates/checkBoxListDelegate.hpp \
		Widgets/checkBoxList.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Widgets/checkBoxList.hpp -o moc_checkBoxList.cpp

moc_rootCommand.cpp: System/rootCommand.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) System/rootCommand.hpp -o moc_rootCommand.cpp

moc_configurationPage.cpp: Pages/pageBase.hpp \
		ui_configurationPage.h \
		Pages/configurationPage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/configurationPage.hpp -o moc_configurationPage.cpp

moc_installationPage.cpp: Pages/pageBase.hpp \
		ui_installationPage.h \
		System/chroot.hpp \
		Pages/installationPage.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) Pages/installationPage.hpp -o moc_installationPage.cpp

moc_chroot.cpp: System/chroot.hpp
	/usr/bin/moc $(DEFINES) $(INCPATH) System/chroot.hpp -o moc_chroot.cpp

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: Resources.qrc \
		Icons/help.png \
		Icons/media-flash-smart-media.png \
		Icons/Release.png \
		Icons/Disks.png \
		Icons/drive-harddisk.png \
		Icons/Time.png \
		Icons/Users.png \
		Icons/information.png \
		Icons/error.png \
		Icons/License.png \
		Icons/prev.png \
		Icons/next.png \
		Icons/status.png \
		Icons/Installation.png \
		Icons/drive-removable-media-usb-pendrive.png \
		Icons/drive-removable-media.png \
		Icons/drive-removable-media-usb.png \
		Icons/Confguration.png \
		Icons/exit.png \
		Icons/Packages.png \
		Icons/current.png \
		Icons/done.png
	/usr/bin/rcc -name Resources Resources.qrc -o qrc_Resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_diskPage.h ui_licensePage.h ui_loadingPage.h ui_mainwindow.h ui_packagesPage.h ui_releasePage.h ui_timepage.h ui_usersPage.h ui_configurationPage.h ui_installationPage.h
compiler_uic_clean:
	-$(DEL_FILE) ui_diskPage.h ui_licensePage.h ui_loadingPage.h ui_mainwindow.h ui_packagesPage.h ui_releasePage.h ui_timepage.h ui_usersPage.h ui_configurationPage.h ui_installationPage.h
ui_diskPage.h: UI/diskPage.ui
	/usr/bin/uic UI/diskPage.ui -o ui_diskPage.h

ui_licensePage.h: UI/licensePage.ui
	/usr/bin/uic UI/licensePage.ui -o ui_licensePage.h

ui_loadingPage.h: UI/loadingPage.ui
	/usr/bin/uic UI/loadingPage.ui -o ui_loadingPage.h

ui_mainwindow.h: UI/mainwindow.ui
	/usr/bin/uic UI/mainwindow.ui -o ui_mainwindow.h

ui_packagesPage.h: UI/packagesPage.ui
	/usr/bin/uic UI/packagesPage.ui -o ui_packagesPage.h

ui_releasePage.h: UI/releasePage.ui
	/usr/bin/uic UI/releasePage.ui -o ui_releasePage.h

ui_timepage.h: UI/timepage.ui
	/usr/bin/uic UI/timepage.ui -o ui_timepage.h

ui_usersPage.h: UI/usersPage.ui
	/usr/bin/uic UI/usersPage.ui -o ui_usersPage.h

ui_configurationPage.h: UI/configurationPage.ui
	/usr/bin/uic UI/configurationPage.ui -o ui_configurationPage.h

ui_installationPage.h: UI/installationPage.ui
	/usr/bin/uic UI/installationPage.ui -o ui_installationPage.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		Pages/packagesPage.hpp \
		ui_packagesPage.h \
		Pages/diskPage.hpp \
		System/drive.h \
		ui_diskPage.h \
		Delegates/partitionSizeDelegate.hpp \
		Delegates/comboBoxListDelegate.hpp \
		Pages/licensePage.hpp \
		ui_licensePage.h \
		Pages/releasePage.hpp \
		ui_releasePage.h \
		Pages/userspage.hpp \
		ui_usersPage.h \
		Widgets/checkBoxList.hpp \
		Delegates/checkBoxListDelegate.hpp \
		Pages/timepage.hpp \
		ui_timepage.h \
		Pages/configurationPage.hpp \
		ui_configurationPage.h \
		Pages/installationPage.hpp \
		ui_installationPage.h \
		System/chroot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

checkBoxListDelegate.o: Delegates/checkBoxListDelegate.cpp Delegates/checkBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkBoxListDelegate.o Delegates/checkBoxListDelegate.cpp

comboBoxListDelegate.o: Delegates/comboBoxListDelegate.cpp Delegates/comboBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboBoxListDelegate.o Delegates/comboBoxListDelegate.cpp

paritionSizeDelegate.o: Delegates/paritionSizeDelegate.cpp Delegates/partitionSizeDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paritionSizeDelegate.o Delegates/paritionSizeDelegate.cpp

progressbarDelegate.o: Delegates/progressbarDelegate.cpp Delegates/progressbarDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progressbarDelegate.o Delegates/progressbarDelegate.cpp

diskPage.o: Pages/diskPage.cpp Pages/diskPage.hpp \
		System/drive.h \
		Pages/pageBase.hpp \
		ui_diskPage.h \
		Delegates/partitionSizeDelegate.hpp \
		Delegates/comboBoxListDelegate.hpp \
		Delegates/progressbarDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskPage.o Pages/diskPage.cpp

licensePage.o: Pages/licensePage.cpp Pages/licensePage.hpp \
		Pages/pageBase.hpp \
		ui_licensePage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o licensePage.o Pages/licensePage.cpp

loadingpage.o: Pages/loadingpage.cpp Pages/loadingpage.hpp \
		Pages/pageBase.hpp \
		ui_loadingPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadingpage.o Pages/loadingpage.cpp

packagesPage.o: Pages/packagesPage.cpp Pages/packagesPage.hpp \
		ui_packagesPage.h \
		Pages/pageBase.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packagesPage.o Pages/packagesPage.cpp

pageBase.o: Pages/pageBase.cpp Pages/pageBase.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pageBase.o Pages/pageBase.cpp

releasePage.o: Pages/releasePage.cpp Pages/releasePage.hpp \
		Pages/pageBase.hpp \
		ui_releasePage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o releasePage.o Pages/releasePage.cpp

timepage.o: Pages/timepage.cpp Pages/timepage.hpp \
		Pages/pageBase.hpp \
		ui_timepage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timepage.o Pages/timepage.cpp

userspage.o: Pages/userspage.cpp Pages/userspage.hpp \
		Pages/pageBase.hpp \
		ui_usersPage.h \
		Widgets/checkBoxList.hpp \
		Delegates/checkBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userspage.o Pages/userspage.cpp

drive.o: System/drive.cpp System/drive.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drive.o System/drive.cpp

checkBoxList.o: Widgets/checkBoxList.cpp Widgets/checkBoxList.hpp \
		Delegates/checkBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkBoxList.o Widgets/checkBoxList.cpp

rootCommand.o: System/rootCommand.cpp System/rootCommand.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rootCommand.o System/rootCommand.cpp

configurationPage.o: Pages/configurationPage.cpp Pages/configurationPage.hpp \
		Pages/pageBase.hpp \
		ui_configurationPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurationPage.o Pages/configurationPage.cpp

installationPage.o: Pages/installationPage.cpp Pages/installationPage.hpp \
		Pages/pageBase.hpp \
		ui_installationPage.h \
		System/chroot.hpp \
		Pages/packagesPage.hpp \
		ui_packagesPage.h \
		Pages/diskPage.hpp \
		System/drive.h \
		ui_diskPage.h \
		Delegates/partitionSizeDelegate.hpp \
		Delegates/comboBoxListDelegate.hpp \
		Pages/timepage.hpp \
		ui_timepage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o installationPage.o Pages/installationPage.cpp

chroot.o: System/chroot.cpp System/chroot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chroot.o System/chroot.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_checkBoxListDelegate.o: moc_checkBoxListDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkBoxListDelegate.o moc_checkBoxListDelegate.cpp

moc_comboBoxListDelegate.o: moc_comboBoxListDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboBoxListDelegate.o moc_comboBoxListDelegate.cpp

moc_partitionSizeDelegate.o: moc_partitionSizeDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partitionSizeDelegate.o moc_partitionSizeDelegate.cpp

moc_progressbarDelegate.o: moc_progressbarDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_progressbarDelegate.o moc_progressbarDelegate.cpp

moc_diskPage.o: moc_diskPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskPage.o moc_diskPage.cpp

moc_licensePage.o: moc_licensePage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_licensePage.o moc_licensePage.cpp

moc_loadingpage.o: moc_loadingpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadingpage.o moc_loadingpage.cpp

moc_packagesPage.o: moc_packagesPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_packagesPage.o moc_packagesPage.cpp

moc_pageBase.o: moc_pageBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pageBase.o moc_pageBase.cpp

moc_releasePage.o: moc_releasePage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_releasePage.o moc_releasePage.cpp

moc_timepage.o: moc_timepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timepage.o moc_timepage.cpp

moc_userspage.o: moc_userspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userspage.o moc_userspage.cpp

moc_checkBoxList.o: moc_checkBoxList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkBoxList.o moc_checkBoxList.cpp

moc_rootCommand.o: moc_rootCommand.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rootCommand.o moc_rootCommand.cpp

moc_configurationPage.o: moc_configurationPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configurationPage.o moc_configurationPage.cpp

moc_installationPage.o: moc_installationPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_installationPage.o moc_installationPage.cpp

moc_chroot.o: moc_chroot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chroot.o moc_chroot.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

